# Generated by Django 4.2.9 on 2024-01-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_offered', models.PositiveIntegerField(default=1)),
                ('vac_accepted', models.PositiveIntegerField(default=1)),
                ('vac_regretted', models.PositiveIntegerField(default=0)),
                ('financial', models.CharField(choices=[('gratis', 'Gratis'), ('non-gratis', 'Non-Gratis'), ('partial-gratis', 'Partial-Gratis')], default='Gratis', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evcats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Course', 'Course'), ('SME', 'SME'), ('Visit', 'Visit'), ('Exercise', 'Exercise'), ('Seminar', 'Seminar'), ('Symposium', 'Symposium'), ('Misc', 'Misc')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GovtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('go_number', models.CharField(max_length=100, unique=True)),
                ('go_pub_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Svcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Army', 'Army'), ('Navy', 'Navy'), ('Air Force', 'Air Force'), ('AFD', 'AFD')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_allocated', models.PositiveIntegerField(default=0)),
                ('course_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courseoffer')),
                ('svc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.svcs')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Number', models.CharField(max_length=200)),
                ('Rank', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('svc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.svcs')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institute_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.evcats')),
                ('participants', models.ManyToManyField(related_name='courses', to='myapp.participants')),
            ],
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events'),
        ),
        migrations.AddField(
            model_name='courseoffer',
            name='ff_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country'),
        ),
    ]
