# Generated by Django 4.2.9 on 2024-01-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
