# Generated by Django 4.2.9 on 2024-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_events_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='govtorder',
            name='days_involved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
