# Generated by Django 4.2.9 on 2024-01-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_govtorder_days_involved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='govtorder',
            options={'ordering': ['-go_pub_date']},
        ),
        migrations.AddField(
            model_name='govtorder',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.country'),
        ),
        migrations.AddField(
            model_name='govtorder',
            name='govt_order_document',
            field=models.FileField(blank=True, null=True, upload_to='govt_order_documents/'),
        ),
        migrations.AddField(
            model_name='govtorder',
            name='svc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.svcs'),
        ),
        migrations.AlterField(
            model_name='evcats',
            name='name',
            field=models.CharField(choices=[('Course', 'Course'), ('SMEE', 'SMEE'), ('Visit', 'Visit'), ('Exercise', 'Exercise'), ('Seminar', 'Seminar'), ('Symposium', 'Symposium'), ('Misc', 'Misc')], max_length=100),
        ),
    ]
