# Generated by Django 4.2.9 on 2024-01-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_govtorder_options_govtorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='govt_order',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='myapp.govtorder'),
        ),
    ]
